name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11 # Specify your Terraform version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Specify your AWS region

      - name: Empty S3 Bucket
        run: |
          aws s3 rm s3://hypha-webslinger --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Destroy
        run: terraform destroy -auto-approve 

      - name: Clean up Kubernetes resources
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          git clone https://github.com/fredritchie/3-tier-eks-manifests.git
          cd 3-tier-eks-manifests
          # Function to safely delete Kubernetes resources
          delete_resource() {
            kubectl delete -f $1 || echo "Failed to delete $1. It may not exist."
          }
          delete_resource frontendCICD.yaml
          delete_resource backend.yaml
          delete_resource service.yaml
          delete_resource secret.yaml
          delete_resource database.yaml
